name: Publish Package to GitHub Packages

on:
  push:
    tags:
      - 'v*'  # Triggers when a new tag like v0.1.0 is pushed

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Required to publish to GitHub Packages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@CravingsInc'  # Replace with your GitHub org or username

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
